FROM python:3.11-slim

WORKDIR /app

# Copy only what the worker needs
COPY analyzer.py .
COPY worker.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "worker.py"]
